/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:649434:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:649434:

public void opt_sin_clicked1(GOption source, GEvent event) { //_CODE_:opt_sin:664446:
  println("opt_sin - GOption >> GEvent." + event + " @ " + millis());
  setWave_sin();
} //_CODE_:opt_sin:664446:

public void opt_rect_clicked1(GOption source, GEvent event) { //_CODE_:opt_rect:817226:
  println("opt_rect - GOption >> GEvent." + event + " @ " + millis());
  setWave_rectangle();
} //_CODE_:opt_rect:817226:

public void cb_line_clicked1(GCheckbox source, GEvent event) { //_CODE_:cb_line:438141:
  println("cb_line - GCheckbox >> GEvent." + event + " @ " + millis());
  if (event == GEvent.SELECTED) {
    plot_wave.plot_line = true;
    plot_spec.plot_line = true;
  }
  else {
    plot_wave.plot_line = false;
    plot_spec.plot_line = false;
  }
  updateGraph();
} //_CODE_:cb_line:438141:

public void cb_impulse_clicked1(GCheckbox source, GEvent event) { //_CODE_:cb_impulse:998441:
  println("cb_impulse - GCheckbox >> GEvent." + event + " @ " + millis());
  if (event == GEvent.SELECTED) {
    plot_wave.plot_impulse = true;
    plot_spec.plot_impulse = true;
  }
  else {
    plot_wave.plot_impulse = false;
    plot_spec.plot_impulse = false;
  }
  updateGraph();

} //_CODE_:cb_impulse:998441:

public void cb_marker_clicked1(GCheckbox source, GEvent event) { //_CODE_:cb_marker:482368:
  println("cb_marker - GCheckbox >> GEvent." + event + " @ " + millis());
  if (event == GEvent.SELECTED) {
    plot_wave.plot_marker = true;
    plot_spec.plot_marker = true;
  }
  else {
    plot_wave.plot_marker = false;
    plot_spec.plot_marker = false;
  }
  updateGraph();
} //_CODE_:cb_marker:482368:

public void dl_nsamples_click1(GDropList source, GEvent event) { //_CODE_:dl_nsamples:234957:
  println("dl_nsamples - GDropList >> GEvent." + event + " @ " + millis());
  println(source.getSelectedText());
  setNSamples(int(source.getSelectedText()));
} //_CODE_:dl_nsamples:234957:

public void tf_sigfreq_change1(GTextField source, GEvent event) { //_CODE_:tf_sigfreq:229569:
  println("tf_sigfreq - GTextField >> GEvent." + event + " @ " + millis());
  if (isFloat(source.getText())) {
    setSignalFrequency(float(source.getText()));
  }
} //_CODE_:tf_sigfreq:229569:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  button1 = new GButton(this, 230, 320, 80, 30);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click1");
  sp_spec = new GSketchPad(this, 10, 380, 880, 300);
  togGroup_waveType = new GToggleGroup();
  opt_sin = new GOption(this, 320, 320, 120, 20);
  opt_sin.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  opt_sin.setText("Sin");
  opt_sin.setOpaque(false);
  opt_sin.addEventHandler(this, "opt_sin_clicked1");
  opt_rect = new GOption(this, 450, 320, 120, 20);
  opt_rect.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  opt_rect.setText("Rectangular");
  opt_rect.setOpaque(false);
  opt_rect.addEventHandler(this, "opt_rect_clicked1");
  togGroup_waveType.addControl(opt_sin);
  opt_sin.setSelected(true);
  togGroup_waveType.addControl(opt_rect);
  sp_wave = new GSketchPad(this, 10, 10, 880, 300);
  cb_line = new GCheckbox(this, 10, 320, 50, 20);
  cb_line.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  cb_line.setText("Line");
  cb_line.setOpaque(false);
  cb_line.addEventHandler(this, "cb_line_clicked1");
  cb_line.setSelected(true);
  cb_impulse = new GCheckbox(this, 70, 320, 70, 20);
  cb_impulse.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  cb_impulse.setText("Impulse");
  cb_impulse.setOpaque(false);
  cb_impulse.addEventHandler(this, "cb_impulse_clicked1");
  cb_impulse.setSelected(true);
  cb_marker = new GCheckbox(this, 150, 320, 70, 20);
  cb_marker.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  cb_marker.setText("Marker");
  cb_marker.setOpaque(false);
  cb_marker.addEventHandler(this, "cb_marker_clicked1");
  cb_marker.setSelected(true);
  dl_nsamples = new GDropList(this, 450, 350, 90, 140, 6);
  dl_nsamples.setItems(loadStrings("list_234957"), 0);
  dl_nsamples.addEventHandler(this, "dl_nsamples_click1");
  label1 = new GLabel(this, 320, 350, 120, 20);
  label1.setText("Number of Samples");
  label1.setOpaque(false);
  label2 = new GLabel(this, 560, 350, 120, 20);
  label2.setText("Signal frequency [Hz]");
  label2.setOpaque(false);
  tf_sigfreq = new GTextField(this, 690, 350, 70, 20, G4P.SCROLLBARS_NONE);
  tf_sigfreq.setOpaque(true);
  tf_sigfreq.addEventHandler(this, "tf_sigfreq_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GSketchPad sp_spec; 
GToggleGroup togGroup_waveType; 
GOption opt_sin; 
GOption opt_rect; 
GSketchPad sp_wave; 
GCheckbox cb_line; 
GCheckbox cb_impulse; 
GCheckbox cb_marker; 
GDropList dl_nsamples; 
GLabel label1; 
GLabel label2; 
GTextField tf_sigfreq; 

